Fix debug build when enable_plugins==0
There's lots of link errors in debug builds with enable_plugins==0:

../../content/browser/loader/buffered_resource_handler.cc:441: error: undefined reference to 'content::PluginServiceImpl::GetInstance()'
../../content/browser/renderer_host/render_message_filter.cc:666: error: undefined reference to 'content::PluginServiceImpl::GetInstance()'
../../content/browser/renderer_host/render_message_filter.cc:671: error: undefined reference to 'content::PluginServiceImpl::GetInstance()'
../../content/browser/renderer_host/render_message_filter.cc:679: error: undefined reference to 'content::PluginServiceImpl::GetInstance()'
../../content/browser/renderer_host/render_message_filter.cc:727: error: undefined reference to 'content::PluginServiceImpl::OpenChannelToNpapiPlugin(int, int, GURL const&, GURL const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, content::PluginProc
essHost::Client*)'
../../content/browser/renderer_host/render_message_filter.cc:737: error: undefined reference to 'content::PluginServiceImpl::OpenChannelToPpapiPlugin(int, base::FilePath const&, base::FilePath const&, content::PpapiPluginProcessHost::PluginClient*)'
../../content/browser/renderer_host/render_message_filter.cc:759: error: undefined reference to 'content::BrowserPpapiHostImpl::AddInstance(int, content::PepperRendererInstanceData const&)'
../../content/browser/renderer_host/render_message_filter.cc:762: error: undefined reference to 'content::PpapiPluginProcessHost::DidCreateOutOfProcessInstance(int, int, content::PepperRendererInstanceData const&)'
../../content/browser/renderer_host/render_message_filter.cc:776: error: undefined reference to 'content::BrowserPpapiHostImpl::DeleteInstance(int)'
../../content/browser/renderer_host/render_message_filter.cc:779: error: undefined reference to 'content::PpapiPluginProcessHost::DidDeleteOutOfProcessInstance(int, int)'
../../content/browser/renderer_host/render_message_filter.cc:789: error: undefined reference to 'content::PluginServiceImpl::OpenChannelToPpapiBroker(int, base::FilePath const&, content::PpapiPluginProcessHost::BrokerClient*)'
../../content/child/npapi/npobject_util.cc:131: error: undefined reference to 'content::PluginHost::Singleton()'
../../content/child/npapi/npobject_util.cc:131: error: undefined reference to 'content::PluginHost::PatchNPNetscapeFuncs(_NPNetscapeFuncs*)'

These do not occur in release builds because the dead code containing
these references is removed.

Review URL: https://codereview.chromium.org/66993007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@235624 0039d316-1c4b-4281-b951-d872f2087c98