Fix some gcc 4.4 issues when compiling with toolkit_views.
Most of these squash harmless compiler warnings but the custom_button.cc
change fixes a real problem with the accelerator key bitmask calculation
(+ preceeds << in terms of operator precedence)

The change to tab_strip.cc is ugly but it fixes the following error:

chrome/browser/views/tabs/tab_strip.cc: In member function
‘void TabStrip::StartRemoveTabAnimation(int, TabContents*)’:
chrome/browser/views/tabs/tab_strip.cc:201: error: assuming
signed overflow does not occur when assuming that
(X - c) > X is always false

As an added bonus, this makes the Linux shared build of toolkit_views
work too.

Review URL: http://codereview.chromium.org/199025

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@25602 0039d316-1c4b-4281-b951-d872f2087c98