Revert 237848 "Use LatencyInfoSwapPromise to track LatencyInfo t..."
Speculative revert to see if this broke views_unittests, event_unittests, and
aura_unittests to be crashed or hung. Example:

E:\b\build\slave\Win8_Aura\build\src\out\Debug\events_unittests.exe --brave-new-test-launcher --test-launcher-bot-mode --gtest_print_time --gtest_output=xml:E:\b\build\slave\Win8_Aura\build\gtest-results\events_unittests\events_unittests.xml
IMPORTANT DEBUGGING NOTE: batches of tests are run inside their
own process. For debugging a test inside a debugger, use the
--gtest_filter=<your_test_name> flag along with
--single-process-tests.
Enabling defaults optimized for continuous integration bots.
Using sharding settings from environment. This is shard 0/1
Using 8 parallel jobs.
[1128/165136:ERROR:launch_win.cc(166)] : Access is denied.
[1128/165136:ERROR:launch_win.cc(166)] : Access is denied.
Failed to get out-of-band test success data, dumping full stdio below:

[1/29] EventDispatcherTest.EventDispatchOrder (UNKNOWN)
[2/29] EventDispatcherTest.EventDispatchPhase (UNKNOWN)
[3/29] EventDispatcherTest.EventDispatcherDestroyedDuringDispatch (UNKNOWN)
[4/29] EventDispatcherTest.EventDispatcherInvalidateTarget (UNKNOWN)
[5/29] EventDispatcherTest.EventHandlerDestroyedDuringDispatch (UNKNOWN)
[6/29] EventDispatcherTest.EventHandlerAndDispatcherDestroyedDuringDispatch (UNKNOWN)
[7/29] LatencyInfoTest.AddTwoSeparateEvent (UNKNOWN)
[8/29] LatencyInfoTest.AddTwoSameEvent (UNKNOWN)
[9/29] LatencyInfoTest.MergeTwoSeparateEvent (UNKNOWN)
[10/29] LatencyInfoTest.MergeTwoSameEvent (UNKNOWN)
Too many badly broken tests (10), exiting now.
[1128/165136:ERROR:launch_win.cc(166)] : Access is denied.
Error:  no element found: line 1, column 0
No data was available to update the JSON results
exit code (as seen by runtest.py): 1
@@@STEP_FAILURE@@@
@@@STEP_TEXT@events_unittests@@@
@@@STEP_TEXT@crashed or hung@@@

> Use LatencyInfoSwapPromise to track LatencyInfo through compositor
> 
> Originally we cache LatencyInfo directly in compositor. Now that
> with the support of SwapPromise, we can use LatencyInfoSwapPromise
> to track the LatencyInfo.
> 
> BUG=246034
> TEST=Input LatencyInfo are still correctly passed to output surface
>      through LatencyInfoSwapPromise.
> 
> Review URL: https://codereview.chromium.org/81533002

TBR=miletus@chromium.org

Review URL: https://codereview.chromium.org/96073002

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@237857 0039d316-1c4b-4281-b951-d872f2087c98