Fix bug caught by clang's -Wlogical-not-parentheses
../../chrome/browser/ui/views/download/download_item_view.cc:910:7: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
  if (!source_type == ui::MENU_SOURCE_MOUSE) {
      ^            ~~
../../chrome/browser/ui/views/download/download_item_view.cc:910:7: note: add parentheses after the '!' to evaluate the comparison first
  if (!source_type == ui::MENU_SOURCE_MOUSE) {
      ^
       (                                   )
../../chrome/browser/ui/views/download/download_item_view.cc:910:7: note: add parentheses around left hand side expression to silence this warning
  if (!source_type == ui::MENU_SOURCE_MOUSE) {
      ^
      (           )
1 error generated.

Since MENU_SOURCE_MOUSE is equal to 1, this does change behavior.

BUG=262248
R=sadrul@chromium.org, varunjain@chromium.org

Review URL: https://codereview.chromium.org/19863006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@212958 0039d316-1c4b-4281-b951-d872f2087c98