Fix some clang compilation errors due to chromium-style.
This morning a fresh Chromium checkout failed to compile under Clang:
error: [chromium-style] Overriding method must have "virtual" keyword

BUG=
TBR=dcheng,pkasting

Review URL: https://chromiumcodereview.appspot.com/14852005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@198092 0039d316-1c4b-4281-b951-d872f2087c98