Revert 227760 "Add autoclick accessibility feature to ash."
This test seems to still fail, although differently:
http://build.chromium.org/p/chromium.win/builders/Win%20Aura%20Tests%20%281%29/builds/7105

AutoclickTest.KeyModifiersReleased: 
c:\b\build\slave\win_aura_builder\build\src\ash\autoclick\autoclick_unittest.cc(204): error: Value of: events[0].flags() & ui::EF_ALT_DOWN
Actual: 0
Expected: ui::EF_ALT_DOWN
Which is: 8

AutoclickTest.MultipleKeyModifiers: 
c:\b\build\slave\win_aura_builder\build\src\ash\autoclick\autoclick_unittest.cc(183): error: Value of: events[0].flags() & modifier_flags
Actual: 0
Expected: modifier_flags
Which is: 14
c:\b\build\slave\win_aura_builder\build\src\ash\autoclick\autoclick_unittest.cc(184): error: Value of: events[1].flags() & modifier_flags
Actual: 0
Expected: modifier_flags
Which is: 14

AutoclickTest.SingleKeyModifier: 
c:\b\build\slave\win_aura_builder\build\src\ash\autoclick\autoclick_unittest.cc(172): error: Value of: events[0].flags() & ui::EF_SHIFT_DOWN
Actual: 0
Expected: ui::EF_SHIFT_DOWN
Which is: 2
c:\b\build\slave\win_aura_builder\build\src\ash\autoclick\autoclick_unittest.cc(173): error: Value of: events[1].flags() & ui::EF_SHIFT_DOWN
Actual: 0
Expected: ui::EF_SHIFT_DOWN
Which is: 2


> Add autoclick accessibility feature to ash.
> 
> BUG=272401
> TEST=added unit tests
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=226895
> 
> Review URL: https://codereview.chromium.org/24191002

TBR=tengs@chromium.org

Review URL: https://codereview.chromium.org/26732004

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@227812 0039d316-1c4b-4281-b951-d872f2087c98