Revert 208927 "Move ShellWindow into apps component."
broke build:

../../chrome/browser/ui/apps/chrome_shell_window_delegate.cc:7:31: fatal error: base/stringprintf.h: No such file or directory

(I think it was moved to base/strings/stringprintf.h)

> Move ShellWindow into apps component.
> 
> This involves creating a new delegate type, ShellWindow::Delegate, which
> is implemented in chrome.
> 
> BUG=159366
> 
> Review URL: https://chromiumcodereview.appspot.com/16702003

TBR=benwells@chromium.org

Review URL: https://codereview.chromium.org/18062007

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@208929 0039d316-1c4b-4281-b951-d872f2087c98