Revert 217722 "[Sheriff] Disable SafeBrowsingBlockingPageTest.Ma..."
Because the patch broke compile on Win Aura builder.

c.f.
FAILED: ninja -t msvc -e environment.x86 -- C:\b\build\goma\gomacc.exe "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\cl.exe" /nologo /showIncludes /FC @obj\chrome\browser\safe_browsing\browser_tests.safe_browsing_blocking_page_test.obj.rsp /c ..\..\chrome\browser\safe_browsing\safe_browsing_blocking_page_test.cc /Foobj\chrome\browser\safe_browsing\browser_tests.safe_browsing_blocking_page_test.obj /Fdobj\chrome\browser_tests.pdb 
c:\b\build\slave\win_aura_builder\build\src\chrome\browser\safe_browsing\safe_browsing_blocking_page_test.cc(717) : error C2504: 'DISABLED_SafeBrowsingBlockingPageTest' : base class undefined
...

> [Sheriff] Disable SafeBrowsingBlockingPageTest.MalwareIframeReportDetails on Win Aura because it is flaky.
> 
> BUG=273302
> TBR=mattm@chromium.org
> 
> Review URL: https://codereview.chromium.org/23227003

TBR=rlp@chromium.org

Review URL: https://codereview.chromium.org/22996005

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@217732 0039d316-1c4b-4281-b951-d872f2087c98