mac: Unbreak shared build.
It was broken by https://chromiumcodereview.appspot.com/10384140.

SOLINK_MODULE(target) out/Release/remoting_host_prefpane.prefPane/Contents/MacOS/remoting_host_prefpane
Undefined symbols:
  "_modp_b64_decode", referenced from:
      -[Me2MePreferencePane onApply:] in me2me_preference_pane.o
ld: symbol(s) not found

This doesn't happen in the components build because the prefpane still
depends on base via

 tools/gyp-explain.py     remoting_host_prefpane modp_b64
These paths lead from remoting/remoting.gyp:remoting_host_prefpane#target to third_party/modp_b64/modp_b64.gyp:modp_b64#target:
remoting/remoting.gyp:remoting_host_prefpane#target -> remoting/remoting.gyp:remoting_base#target -> base/base.gyp:base#target -> third_party/modp_b64/modp_b64.gyp:modp_b64#target

BUG=none
TEST=none
TBR=lambroslambrou

Review URL: https://chromiumcodereview.appspot.com/10389178

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@137489 0039d316-1c4b-4281-b951-d872f2087c98