Revert 155224 - Add is_fullscreen to video updates
http://build.chromium.org/p/chromium/builders/Win%20Aura/builds/21280/steps/ash_unittests/logs/stdio#failure1
[ RUN      ] VideoDetectorTest.FullscreenWindow
wm\video_detector_unittest.cc(250): error: Value of:
observer_->num_invocations()
  Actual: 0
  Expected: 1
  wm\video_detector_unittest.cc(251): error: Value of:
  observer_->num_fullscreens()
    Actual: 0
    Expected: 1
    [  FAILED  ] VideoDetectorTest.FullscreenWindow (138 ms)

This is a re-attempt at http://codereview.chromium.org/10905026/, which ended up
being reverted.

The crash that caused the revert was actually due to powerd not being able to
parse the protobuf correctly. https://gerrit.chromium.org/gerrit/32243/ corrects
this issue, so once that CL lands this CL is good to go. I confirmed the
combination of CLs works correctly.

This is the original CL description:

This adds a boolean to the video update message sent to powerd that indicates
whether or not the video playing window is fullscreen'd. This is information
used in powerd for controlling when to enable/disable keyboard
backlights. Specifically if video is playing and fullscreen we assume that the
user is doing something like watching a movie so will disable backlight.

An additional change that I have made is to convert the message being sent from
an int64 to a protobuffer that contains a int64 and a boolean. Currently, since
the receiver of this message does not live in the same repo it means that
everytime one wants to change the message format there is a small window where
bad builds can be generated or one has to land two changes to the other repo,
one to add handling of the new message format and then a second one to remove
the old format. Converting to a protobuffer means that for common cases this
issues are removed.

This CL depends on CLs for power_manager
(https://gerrit.chromium.org/gerrit/32092/), one for system_api
(https://gerrit.chromium.org/gerrit/31916), and a DEPS
roll(http://codereview.chromium.org/10915032/).  There will be future CLs for
power_manager that will use this information and more thourghly tests this code.

BUG=chrome-os-partner:9203
TEST=Run updated unittests.
     Confirm there is no messages in the cros logs about this method being
     mishandled.
     Make sure that powerd is not crashing due to protocol buffer processing
     failing.


Review URL: https://chromiumcodereview.appspot.com/10916123

TBR=rharrison@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10928037

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@155232 0039d316-1c4b-4281-b951-d872f2087c98