base: Move CaseInsensitiveCompare traits into the base namespace.
This should fix conflicts like:
2>d:\src\chromium_src2\src\base/string_util.h(480) : error C2904: 'CaseInsensitiveCompare' : name already used for a template in the current scope
2>        d:\src\chromium_src2\src\third_party\xulrunner-sdk\win\include\xpcom\nsStringAPI.h(1406) : see declaration of 'CaseInsensitiveCompare'

Reported-by: Jeff Timanus <twiz@google.com>

BUG=None
TEST=trybots

Review URL: http://codereview.chromium.org/4366001

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@64877 0039d316-1c4b-4281-b951-d872f2087c98