Fix a build error related to case-sensitive file system on Mac OS.
Compiling the latest source tree on case-sensitive file system, currently breaks at:

../../chrome/browser/ui/cocoa/browser_window_cocoa_unittest.mm:17:9: fatal error: 'third_party/ocmock/ocmock/OCMock.h' file not found
#import "third_party/ocmock/ocmock/OCMock.h"
        ^
1 error generated.
[343/1218] LINK soft_gpu_tests, POSTBUILDS
ninja: build stopped: subcommand failed.

It seems that 'third_party/ocmock/OCMock/OCMock.h' is correct.

Review URL: https://chromiumcodereview.appspot.com/12077021

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@179625 0039d316-1c4b-4281-b951-d872f2087c98