Revert of WebRTC browser tests will now render during tests. (https://codereview.chromium.org/153623005/)
Reason for revert:
This CL breaks compile, e.g. ../../chrome/browser/media/webrtc_browsertest_base.cc -o obj/chrome/browser/media/browser_tests.webrtc_browsertest_base.o
In file included from ../../chrome/browser/media/webrtc_browsertest_base.cc:5:
../../chrome/browser/media/webrtc_browsertest_base.h:33:3: error: [chromium-style] Overriding method must have "virtual" keyword.
  void SetUp() OVERRIDE;
  ^
  virtual 
1 error generated.

(http://build.chromium.org/p/chromium.mac/builders/Mac%20Builder%20%28dbg%29/builds/61654/steps/compile/logs/stdio as an example)

Original issue's description:
> WebRTC browser tests will now render during tests.
> 
> This is a speculative fix to try to fix the video quality test timeouts
> on the FYI bots. I noticed the browser tests did not run with pixel
> output enabled, which means they don't really render. Not sure how it
> is related to the gUM failures in the bug, but this will at least make
> it easier to see what's going on when it fails.
> 
> R=xians@chromium.org
> BUG=340609
> NOTRY=True
> 
> Committed: https://src.chromium.org/viewvc/chrome?view=rev&revision=249000

TBR=xians@chromium.org,phoglund@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=340609

Review URL: https://codereview.chromium.org/150163006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@249004 0039d316-1c4b-4281-b951-d872f2087c98