Revert 173248, broke building on the official chrome/win bot:
http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Win/builds/15269/steps/compile/logs/stdio#error1

155>  amd_videocard_info_win.cc
155>..\third_party\amd\amd_videocard_info_win.cc(20):error C2146: syntax error : missing ';' before identifier 'GetAMDVideocardType'
155>..\third_party\amd\amd_videocard_info_win.cc(20):error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
155>..\third_party\amd\amd_videocard_info_win.cc(20):error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
155>..\third_party\amd\amd_videocard_info_win.cc(30):error C2065: 'UNKNOWN' : undeclared identifier
155>..\third_party\amd\amd_videocard_info_win.cc(38):error C2065: 'UNKNOWN' : undeclared identifier
155>..\third_party\amd\amd_videocard_info_win.cc(49):error C2065: 'STANDALONE' : undeclared identifier
155>..\third_party\amd\amd_videocard_info_win.cc(50):error C2065: 'SWITCHABLE' : undeclared identifier
155>..\third_party\amd\amd_videocard_info_win.cc(50):error C2065: 'UNKNOWN' : undeclared identifier
155>..\third_party\amd\amd_videocard_info_win.cc(50): warning C4508: 'gpu_info_collector::GetAMDVideocardType' : function should return a value; 'void' return type assumed


> Only collect GL/D3D context specific GPUInfo in GPU process
> 
> Instead of collecting full GPUInfo.  Basic GPUInfo are already collected at Browser process startup time.
> 
> This avoids sandbox issue with libpci on linux.  Also, it makes GPU startup faster.
> 
> BUG=162928,165374
> TEST=manual about:gpu
> TBR=joi
> Review URL: https://codereview.chromium.org/11574049

TBR=zmo@chromium.org
Review URL: https://codereview.chromium.org/11576052

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@173267 0039d316-1c4b-4281-b951-d872f2087c98