remoting: comment out #endif comment.
Needed to cure build errors like:
../../tools/ipc_fuzzer/mutate/rand_util.h:40:8: error: extra tokens at end of #endif directive [-Werror,-Wextra-tokens]
(I don't build this remoting source code but found it during a codesearch after
running afoul of the above error and sending out
https://codereview.chromium.org/150633007/ and figured I'd send you a CR instead
of a heads-up)

Review URL: https://codereview.chromium.org/143663003

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@248177 0039d316-1c4b-4281-b951-d872f2087c98