Revert 232657 "GN: toolchain threading cleanup"
Broke linux clang bots:

../../tools/gn/ninja_helper_unittest.cc:20:9:error: field 'settings' will be initialized after field 'toolchain' [-Werror,-Wreorder]

This happened on your try jobs too.

> GN: toolchain threading cleanup
> 
> Remove the thread-unsafe toolchain pointer on the otherwise-threadsafe Settings object. I replaced it with the toolchain label, and moved the is_default flag from the toolchain to the Settings object.
> 
> This required that I pass the toolchain around in a few more places, but also simplifies some other cases.
> 
> I removed the toolchain prefix from Ninja rules for the default toolchain since that's not necessary any more for GYP compat.
> 
> This fixes an annoying double-free in the toolchain manager. I think my current refactor will clean this up in a later phase.
> 
> R=scottmg@chromium.org
> 
> Review URL: https://codereview.chromium.org/51693002

TBR=brettw@chromium.org

Review URL: https://codereview.chromium.org/46313006

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@232661 0039d316-1c4b-4281-b951-d872f2087c98